# config/appsignal.yml
# Define the "defaults" anchor
default: &defaults
  name: "Medlibra"

production:
  # Loads the defaults in the production environment by referencing the anchor
  <<: *defaults
  # production environment specific configuration
  active: true
